---
applications:
- name: bootnode
  buildpack: binary_buildpack
  health-check-type: process
  memory: 512MB
  command: ./bootnode-start.sh
  env:
    BOOTNODE_PORT: 33445
    BOOTNODE_KEYHEX: "77bd02ffa26e3fb8f324bda24ae588066f1873d95680104de5bc2db9e7b2e510"
  random-route: true
