---
applications:
- name: node-2
  buildpack: binary_buildpack
  health-check-type: process
  memory: 1024MB
  no-route: true
  command: LD_LIBRARY_PATH=bin/ PATH=$PATH:bin/ ./blockmaker-node-start.sh
  services:
  - ip-service
  env:
    NETID: 87234
    BOOTNODE_HASH: 61077a284f5ba7607ab04f33cfde2750d659ad9af962516e159cf6ce708646066cd927a900944ce393b98b95c914e4d6c54b099f568342647a1cd4a262cc0423
    BOOTNODE_PORT: 33445
    OTHER_NODE_PORT: 9000
    NODE_PORT: 9001
    RPC_PORT: 22001
    LISTEN_PORT: 21001
    PRIVATE_CONFIG_FILE: tm2.conf
    DATA_DIR: qdata/dd2
    VOTE_ACCOUNT: "0x0fbdc686b912d7722dc86510934589e0aaf3b55a"
    BLOCKMAKER_ACCOUNT: "0xca843569e3427144cead5e4d5999a3d0ccf92b8e"
