---
applications:
- name: node-6
  buildpack: binary_buildpack
  health-check-type: process
  memory: 200MB
  no-route: true
  command: ./node-start.sh
  env:
    NETID: 87234
    NODE_PORT: 9005
    RPC_PORT: 22005
    LISTEN_PORT: 21005
    PRIVATE_CONFIG_FILE: tm6.conf
    DATA_DIR: qdata/dd6
    OTHER_NODE_PORT: 9000
  services:
    - quorum-discovery
