---
applications:
- name: node-1
  buildpack: binary_buildpack
  health-check-type: process
  memory: 420MB
  no-route: true
  command: ./primary-node-start.sh
  env:
    NETID: 87234
    NODE_PORT: 9000
    RPC_PORT: 22000
    LISTEN_PORT: 21000
    PRIVATE_CONFIG_FILE: tm1.conf
    DATA_DIR: qdata/dd1
  services:
    - quorum-discovery
